apiVersion: csoc.js2.org/v1alpha1
kind: DedicatedSpokeNetwork
metadata:
  name: training-account-jupyterhub-dev
  namespace: spokeclusters-training-account-jupyterhub-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  description: Development spoke network for the training-account JupyterHub
