apiVersion: csoc.js2.org/v1alpha1
kind: FleetOwnershipRegistry
assignments:
  - account: test-poc
    app: hello-app
    environment: dev
    owner: staging
    path: accounts/staging/accounts/test-poc/hello-app/dev
  - account: training-account
    app: jupyterhub
    environment: dev
    owner: staging
    path: accounts/staging/accounts/training-account/jupyterhub/dev
  - account: training-account
    app: registry-cache
    environment: dev
    owner: staging
    path: accounts/staging/accounts/training-account/registry-cache/dev
  - account: training-account
    app: monitoring
    environment: dev
    owner: staging
    path: accounts/staging/accounts/training-account/monitoring/dev
  - account: scale-00
    app: kubernetes
    environment: dev
    owner: staging
    path: accounts/staging/accounts/scale-00/kubernetes/dev
  - account: scale-01
    app: kubernetes
    environment: dev
    owner: staging
    path: accounts/staging/accounts/scale-01/kubernetes/dev
  - account: scale-02
    app: kubernetes
    environment: dev
    owner: staging
    path: accounts/staging/accounts/scale-02/kubernetes/dev
  - account: scale-03
    app: kubernetes
    environment: dev
    owner: staging
    path: accounts/staging/accounts/scale-03/kubernetes/dev
  - account: scale-04
    app: kubernetes
    environment: dev
    owner: staging
    path: accounts/staging/accounts/scale-04/kubernetes/dev
  - account: scale-05
    app: kubernetes
    environment: dev
    owner: staging
    path: accounts/staging/accounts/scale-05/kubernetes/dev
  - account: scale-06
    app: kubernetes
    environment: dev
    owner: staging
    path: accounts/staging/accounts/scale-06/kubernetes/dev
  - account: scale-07
    app: kubernetes
    environment: dev
    owner: staging
    path: accounts/staging/accounts/scale-07/kubernetes/dev
  - account: scale-08
    app: kubernetes
    environment: dev
    owner: staging
    path: accounts/staging/accounts/scale-08/kubernetes/dev
  - account: scale-09
    app: kubernetes
    environment: dev
    owner: staging
    path: accounts/staging/accounts/scale-09/kubernetes/dev
  - account: scale-10
    app: kubernetes
    environment: dev
    owner: staging
    path: accounts/staging/accounts/scale-10/kubernetes/dev
