apiVersion: v1
kind: ConfigMap
metadata:
  name: poc-tenant-dev-cluster-config
  namespace: spokeclusters-csoc-identity
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    csoc.js2.org/config-source: fleet
immutable: true
data:
  environment: dev
  nodeClass: general
  networkConnectionName: poc-tenant-dev-connection
  podCIDR: 192.168.0.0/16
  serviceCIDR: 10.96.0.0/12
