apiVersion: csoc.js2.org/v1alpha1
kind: SpokeCluster
metadata:
  name: poc-tenant-dev
  namespace: spokeclusters-csoc-identity
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  kubernetes:
    minNodes: 2
    maxNodes: 4
  capabilities:
    security: false
    observability: false
  registration:
    enabled: true
    labels:
      csoc.js2.org/customer: poc-tenant
      csoc.js2.org/environment: dev
      csoc.js2.org/ownership: csoc
      csoc.js2.org/hello-app: enabled
