apiVersion: apps.csoc.js2.org/v1alpha1
kind: HelloApp
metadata:
  name: poc-tenant-dev
  namespace: spokeclusters-test-poc
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  target: spoke
  replicas: 2
  applicationAllowedCIDR: 192.0.2.1/32
