apiVersion: delivery.csoc.js2.org/v1alpha1
kind: ApplicationBoundary
metadata: {name: jupyterhub, namespace: spokeclusters-test-poc}
spec:
  registrationRef: {name: test-poc-v2-dev}
  destinationNamespace: jupyterhub
  serviceType: jupyterhub
  sourceRepository: https://github.com/jayadeyemi/config
