apiVersion: csoc.js2.org/v1alpha1
kind: SpokeKeypair
metadata:
  name: scale-10-kubernetes-dev
  namespace: spokeclusters-scale-10-kubernetes-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec: {}
