apiVersion: apps.csoc.js2.org/v1alpha1
kind: SpokeHelloApp
metadata:
  name: poc-tenant-dev
  namespace: spokeclusters-test-poc
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  clusterName: poc-tenant-dev
  replicas: 2
  applicationAllowedCIDR: 129.79.197.56/32
