apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Active development composition; exactly one selected network graph.
resources:
  - identity-config.yaml
  - identity.yaml
  - spoke-config.yaml
  - network.yaml
  - keypair.yaml
  - cluster.yaml
  - hello-app.yaml
