apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - spoke-account.yaml
  - machine-control.yaml
  - machine-system.yaml
  - machine-cpu.yaml
  - network.yaml
  - workload-cluster.yaml
  - pool-system.yaml
  - pool-cpu.yaml
  - registration.yaml
  - foundation.yaml
  - smoke
  - jupyterhub
  - monitoring
