apiVersion: apps.csoc.js2.org/v1alpha1
kind: SpokeArgoCD
metadata:
  name: training-account-jupyterhub-dev
  namespace: spokeclusters-training-account-jupyterhub-dev
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  clusterName: training-account-jupyterhub-dev
