apiVersion: apps.csoc.js2.org/v1alpha1
kind: SpokeHelloApp
metadata:
  name: example-central-hello
  namespace: spokeclusters-example-dedicated
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  clusterName: example-dedicated
  replicas: 2
  applicationAllowedCIDR: 192.0.2.1/32
