apiVersion: csoc.js2.org/v1alpha1
kind: SpokeIdentity
metadata:
  name: test-poc-hello-app-dev
  labels:
    csoc.js2.org/account: test-poc
    csoc.js2.org/app: hello-app
    csoc.js2.org/environment: dev
    csoc.js2.org/owner: staging
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec: {}
